#!/bin/bash
sudo apt-get update
sudo apt-get install ruby wget -y
cd /home/ubuntu
wget https://aws-codedeploy-ap-south-1.s3.ap-south-1.amazonaws.com/latest/install
chmod +x ./install
sudo ./install auto
sudo service codedeploy-agent enable 
sudo service codedeploy-agent start